apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: go
spec:
  selector:
    matchLabels:
      app: go
  replicas: 3
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: ghcr.io/sagitur100/devops-interview-argocd:8.0
        ports:
        - containerPort: 8080
