#ArgoCD Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-application
  namespace: argocd
spec:                                                                                                      
  project: go-project
  source:
    repoURL: git@github.com:sagitur100/DevOps-Interview-ArgoCD.git
    targetRevision: main
    path: ./go-deployment.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: go
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
